<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>AppLaunchMenuMvvm</RootNamespace>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <SupportedOSPlatformVersion>10.0.18362.0</SupportedOSPlatformVersion>
	<Nullable>enable</Nullable>
	<BaseOutputPath>$(SolutionDir)bin</BaseOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <AdditionalFiles Include="NativeMethods.txt" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Scripting" Version="*" />
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="*" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="*" />
  </ItemGroup>
</Project>