name: .NET CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: '10.0.x' # Replace with your target version (e.g., '9.0.x', '10.0.x')

    - name: Restore dependencies
      run: dotnet restore

    - name: Build application
      run: dotnet build --configuration Release --no-restore

    - name: Test application
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Publish App
      run: dotnet publish --configuration Release

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: AppLaunchMenu
        path: ./publish